Manage NetworkPolicy/NetNS and client RBAC
appuio/component-openshift-prometheus-proxy pull request #2
Opened 2021-02-18 10:26 UTC by simu

* Configure networkpolicy or netnamespace to allow namespaces labelled   with `appuio.ch/prometheus-proxy=allowed` to access the proxy service.
* Configure RBAC rules to allow serviceaccounts listed in `access.service_accounts` (name/namespace pairs) to access the proxy.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update the ./CHANGELOG.md.

2021-02-18 13:05 UTC, corvus-ch commented on docs/modules/ROOT/pages/references/parameters.adoc
> +=== `access.service_accounts`
Those service accounts are note managed by this component. Once could draw the conclusion, that his component will create them. Please make it more obvious, that this is not the case.

2021-02-18 13:07 UTC, corvus-ch requested changes
Implementation is looking good. Documentation might need some clarification.

2021-02-19 07:36 UTC, srueg approved these changes

2021-02-19 09:36 UTC, corvus-ch approved these changes

2021-02-19 09:51 UTC, merged